src/models/produto.py
import io
import uuid
from base64 import b64decode

from PIL import Image

from sqlalchemy import Boolean, DECIMAL, ForeignKey, Integer, String, Text, Uuid
from sqlalchemy.orm import mapped_column, relationship
from src.modules import db
from src.models.base_mixin import BasicRepositoryMixin, TimeStampMixin

class Produto(db.Model, BasicRepositoryMixin, TimeStampMixin):
    __tablename__ = 'produtos'
    id = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid.uuid4)
    nome = mapped_column(String(100), nullable=False, index=True)
    preco = mapped_column(DECIMAL(10, 2), default=0.00, nullable=False)
    estoque = mapped_column(Integer, default=0)
    ativo = mapped_column(Boolean, default=True, nullable=False)
    possui_foto = mapped_column(Boolean, default=False, nullable=False)
    foto_base64 = mapped_column(Text, default=None, nullable=True)
    foto_mime = mapped_column(String(64), nullable=True, default=None)
    categoria_id = mapped_column(Uuid(as_uuid=True), ForeignKey('categorias.id'))

    categoria = relationship('Categoria',
                             back_populates='lista_de_produtos')

    @property
    def imagem(self):
        if not self.possui_foto:
            saida = io.BytesIO()
            entrada = Image.new('RGB', (480, 480), (128, 128, 128))
            formato = "PNG"
            entrada.save(saida, format=formato)
            conteudo = saida.getvalue()
            tipo = 'image/png'
        else:
            conteudo = b64decode(self.foto_base64)
            tipo = self.foto_mime
        return conteudo, tipo


    def thumbnail(self, size: int = 128):
        if not self.possui_foto:
            saida = io.BytesIO()
            entrada = Image.new('RGB', (size, size), (128, 128, 128))
            formato = "PNG"
            entrada.save(saida, format=formato)
            conteudo = saida.getvalue()
            tipo = 'image/png'
        else:
            arquivo = io.BytesIO(b64decode(self.foto_base64))
            saida = io.BytesIO()
            entrada = Image.open(arquivo)
            formato = entrada.format
            (largura, altura) = entrada.size
            fator = min(size/largura, size/altura)
            novo_tamanho = (int(largura * fator), int(altura * fator))
            entrada.thumbnail(novo_tamanho)
            entrada.save(saida, format=formato)
            conteudo = saida.getvalue()
            tipo = self.foto_mime
        return conteudo, tipo

src/forms/produto.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms.fields.choices import SelectField
from wtforms.fields.numeric import DecimalField, IntegerField
from wtforms.fields.simple import BooleanField, FileField, StringField, SubmitField
from wtforms.validators import InputRequired, Length, NumberRange


class ProdutoForm(FlaskForm):
    nome = StringField(label="Nome do produto",
                       validators=[InputRequired(message="É obrigatório definir o nome do produto"),
                                   Length(max=100, message="O produto pode ter até 100 caracteres")])
    preco = DecimalField(label="Preço", places=2,
                         validators=[InputRequired(message="É obrigatório definir o preço"),
                                     NumberRange(min=0.00, message="Os preços devem ser positivos")])
    estoque = IntegerField(label="Estoque",
                           validators=[InputRequired(message="É preciso definir o estoque"),
                                       NumberRange(min=0, message="O estoque precisa ser positivo")])
    ativo = BooleanField(label="Ativo?")
    foto = FileField(label="Foto do produto",
                     validators=[FileAllowed(['jpg', 'png'], message="Apenas arquivos JPG ou PNG")])
    categoria = SelectField(label="Categoria do produto",
                            validators=[InputRequired(message="Selecione uma categoria")])
    removerfoto = BooleanField(label="Remover a foto atual?",
                               default=False)
    submit = SubmitField()

src/routes/produto.py
from base64 import b64encode

from flask import abort, Blueprint, flash, redirect, render_template, request, Response, url_for
from flask_login import login_required
from werkzeug.exceptions import NotFound

from src.forms.produto import ProdutoForm
from src.models.categoria import Categoria
from src.models.produto import Produto
from src.modules import db

bp = Blueprint('produto', __name__, url_prefix="/produto")


@bp.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    if Categoria.is_empty():
        flash("Impossível adicionar produto. Adcione pelo menos uma categoria",
              category='warning')
        return redirect(url_for('categoria.add'))

    form = ProdutoForm()
    form.submit.label.text = "Adicionar produto"
    categorias = db.session.execute(db.select(Categoria).order_by(Categoria.nome)).scalars()
    form.categoria.choices = [(str(i.id), i.nome) for i in categorias]
    if form.validate_on_submit():
        produto = Produto(nome = form.nome.data, preco = form.preco.data,
                          ativo = form.ativo.data, estoque = form.estoque.data)
        if form.foto.data:
            produto.possui_foto = True
            produto.foto_base64 = (b64encode(request.files[form.foto.name].read()).
                                   decode('ascii'))
            produto.foto_mime = request.files[form.foto.name].mimetype
        else:
            produto.possui_foto = False
            produto.foto_base64 = None
            produto.foto_mime = None
        categoria = Categoria.get_by_id(form.categoria.data)
        if categoria is None:
            flash("Categoria inexistente!", category='danger')
            return redirect(url_for('produto.add'))
        produto.categoria = categoria
        db.session.add(produto)
        db.session.commit()
        flash("Produto adicionado!")
        return redirect(url_for('index'))

    return render_template('produto/add.jinja2', form=form,
                           title="Adicionar novo produto")


@bp.route('/edit/<uuid:produto_id>', methods=['GET', 'POST'])
@login_required
def edit(produto_id):
    produto = Produto.get_by_id(produto_id)
    if produto is None:
        flash("Produto inexistente", category='danger')
        return redirect(url_for('produto.lista'))

    form = ProdutoForm(obj=produto)
    form.submit.label.text = "Alterar produto"
    categorias = db.session.execute(db.select(Categoria).order_by(Categoria.nome)).scalars()
    form.categoria.choices = [(str(i.id), i.nome) for i in categorias]
    if form.validate_on_submit():
        produto.nome = form.nome.data
        produto.preco = form.preco.data
        produto.estoque = form.estoque.data
        produto.ativo = form.ativo.data
        categoria = Categoria.get_by_id(form.categoria.data)
        if form.removerfoto.data:
            produto.possui_foto = False
            produto.foto_mime = None
            produto.foto_base64 = None
        elif form.foto.data:
            produto.possui_foto = True
            produto.foto_base64 = (b64encode(request.files[form.foto.name].read()).
                                   decode('ascii'))
            produto.foto_mime = request.files[form.foto.name].mimetype
        if categoria is None:
            flash("Categoria inexistente!", category='danger')
            return redirect(url_for('produto.lista'))
        produto.categoria = categoria
        db.session.commit()
        flash("Produto alterado", category='success')
        return redirect(url_for('produto.lista'))

    form.categoria.process_data(str(produto.categoria_id))
    return render_template('produto/edit.jinja2', form=form,
                           title="Alterar um produto",
                           produto=produto)


@bp.route('/delete/<uuid:produto_id>', methods=['GET'])
@login_required
def delete(produto_id):
    produto = Produto.get_by_id(produto_id)
    if produto is None:
        flash("Produto inexistente", category='danger')
        return redirect(url_for('produto.lista'))

    db.session.delete(produto)
    db.session.commit()
    flash("Produto removido!", category='success')
    return redirect(url_for('produto.lista'))


@bp.route('/lista', methods=['GET', 'POST'])
@bp.route('/', methods=['GET', 'POST'])
def lista():
    page = request.args.get('page', type=int, default=1)
    pp = request.args.get('pp', type=int, default=25)

    sentenca = db.select(Produto).order_by(Produto.nome)

    try:
        rset = db.paginate(sentenca, page=page, per_page=pp, error_out=True)
    except NotFound:
        flash(f"Não temos produtos na página {page}. Apresentando página 1")
        page = 1
        rset = db.paginate(sentenca, page=page, per_page=pp, error_out=False)

    return render_template('produto/lista.jinja2',
                           title="Lista de produtos",
                           rset=rset,
                           page=page,
                           pp=pp)

@bp.route('/imagem/<uuid:id_produto>', methods=['GET'])
def imagem(id_produto):
    produto = Produto.get_by_id(id_produto)
    if produto is None:
        return abort(404)
    conteudo, tipo = produto.imagem
    return Response(conteudo, mimetype=tipo)

@bp.route('/thumbnail/<uuid:id_produto>/<int:size>', methods=['GET'])
@bp.route('/thumbnail/<uuid:id_produto>', methods=['GET'])
def thumbnail(id_produto, size=128):
    produto = Produto.get_by_id(id_produto)
    if produto is None:
        return abort(404)
    conteudo, tipo = produto.thumbnail(size)
    return Response(conteudo, mimetype=tipo)

src/templates/produto/add.jinja2
{% extends '_layout.jinja2' %}
{% from 'bootstrap5/form.html' import render_field %}

{% block content %}
    <section class="h-100">
        <div class="container h-100">
            <div class="row justify-content-sm-center h-100">
                <div class="col-xxl-6 col-xl-7 col-lg-7 col-md-9 col-sm-12">
                    <div class="card shadow-lg">
                        <div class="card-body p-5">
                            <form action="" method="post" enctype="multipart/form-data">
                                {{ form.csrf_token }}
                                {{ render_field(form.nome) }}
                                {{ render_field(form.categoria) }}
                                {{ render_field(form.estoque) }}
                                {{ render_field(form.ativo) }}
                                {{ render_field(form.foto) }}
                                {{ render_field(form.preco) }}
                                {{ render_field(form.submit) }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

src/templates/produto/add_edit.jinja2
{% extends '_layout.jinja2' %}
{% from 'bootstrap5/form.html' import render_field %}

{% block content %}
    <section class="h-100">
        <div class="container h-100">
            <div class="row justify-content-sm-center h-100">
                <div class="col-xxl-6 col-xl-7 col-lg-7 col-md-9 col-sm-12">
                    <div class="card shadow-lg">
                        <div class="card-body p-5">
                            <form action="" method="post" enctype="multipart/form-data">
                                {{ form.csrf_token }}
                                {{ render_field(form.nome) }}
                                {{ render_field(form.categoria) }}
                                {{ render_field(form.estoque) }}
                                {{ render_field(form.ativo) }}
                                {{ render_field(form.foto) }}
                                {{ render_field(form.preco) }}
                                {{ render_field(form.submit) }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

src/templates/produto/edit.jinja2
{% extends '_layout.jinja2' %}
{% from 'bootstrap5/form.html' import render_field %}
{% from 'utils/menus.jinja2' import sidebar_produto %}

{% block content %}
    <section class="h-100">
        <div class="container d-flex">
            <div class="me-auto">
                {{ sidebar_produto(produto) }}
            </div>
            <div class="ms-5 flex-grow-1">
                <div class="row justify-content-sm-center h-100">
                    <div class="col-xxl-6 col-xl-7 col-lg-7 col-md-9 col-sm-12">
                        <div class="card shadow-lg">
                            <div class="card-body p-5">
                                <form action="" method="post" enctype="multipart/form-data">
                                    {{ form.csrf_token }}
                                    {{ render_field(form.nome) }}
                                    {{ render_field(form.categoria) }}
                                    {{ render_field(form.estoque) }}
                                    {{ render_field(form.ativo) }}
                                    {{ render_field(form.foto) }}
                                    {{ render_field(form.removerfoto) }}
                                    {{ render_field(form.preco) }}
                                    {{ render_field(form.submit) }}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

src/templates/produto/lista.jinja2
{% extends '_layout.jinja2' %}
{% from 'bootstrap5/utils.html' import render_icon %}
{% from 'bootstrap5/pagination.html' import render_pagination %}

{% block content %}
    <div class="row">
        <table class="table table-striped table-hover">
        <thead><tr>
                <th scope="col">Nome do produto</th>
                <th scope="col" class="text-end">Preço</th>
                <th scope="col">Categoria</th>
                <th scope="col">Ativo</th>
                <th scope="col" class="text-end">Estoque</th>
                <th scope="col" class="text-center">Operações</th>
        </tr></thead>
        <tbody>
        {% for produto in rset %}
            <tr><td>{{ produto.nome }}</td>
                <td class="text-end">{{ produto.preco }}</td>
                <td>{{ produto.categoria.nome }}</td>
                <td>{% if produto.ativo %}Ativo{% else %}Inativo{% endif %}</td>
                <td class="text-end">{{ produto.estoque }}</td>
                <td class="text-center">
                    <a href="{{ url_for('produto.delete', produto_id=produto.id) }}"
                       onclick="return confirm('Confirma a remoção do produto?')">{{
                            render_icon('trash', color='danger', size='1.25em')}}</a>
                    <a href="{{ url_for('produto.edit', produto_id = produto.id) }}">{{
                            render_icon('pencil-square', color='primary', size='1.25em') }}</a>
                </td>
        {% endfor %}
        </tbody>
        </table>
    </div>
    <div class="row justify-content-center">
        <div class="clearfix">
            <div class="float-start small">
                Mostrando itens {{ rset.first }} a {{ rset.last }} de um total de
                {{ rset.total }}
            </div>
            <div class="float-end">
            {{ render_pagination(rset,
                                 'produto.lista',
                                 align='right',
                                 size='sm',
                                 args={'pp': pp}) }}
            </div>
        </div>
    </div>
{% endblock %}