src/models/categoria.py
import uuid
from sqlalchemy import String, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship
from src.models.base_mixin import (BasicRepositoryMixin,
                                   TimeStampMixin)
from src.modules import db


class Categoria(db.Model, BasicRepositoryMixin, TimeStampMixin):
    __tablename__ = 'categorias'
    id: Mapped[Uuid] = mapped_column(Uuid(as_uuid=True),
                                     primary_key=True,
                                     default=uuid.uuid4)
    nome: Mapped[str] = mapped_column(String(128),
                                      nullable=False)

    lista_de_produtos = relationship('Produto',
                                     back_populates='categoria',
                                     cascade='all, delete-orphan',
                                     lazy='select')

src/forms/categoria.py
from flask_wtf import FlaskForm
from wtforms.fields.simple import StringField, SubmitField
from wtforms.validators import InputRequired


class NovoCategoriaForm(FlaskForm):
    nome = StringField("Nome da categoria",
                       validators=[
                           InputRequired(message="É obrigatório informar um nome para a categoria")
                       ])
    submit = SubmitField("Adicionar")


class EditCategoriaForm(FlaskForm):
    nome = StringField("Nome da categoria",
                       validators=[
                           InputRequired(message="É obrigatório informar um nome para a categoria")
                       ])
    submit = SubmitField("Alterar")

src/routes/categoria.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required

from src.forms.categoria import EditCategoriaForm, NovoCategoriaForm
from src.modules import db
from src.models.categoria import Categoria
import sqlalchemy as sa

bp = Blueprint('categoria', __name__, url_prefix='/categoria')


@bp.route('/', methods=['GET'])
def lista():
    sentenca = sa.select(Categoria).order_by(Categoria.nome)
    rset = db.session.execute(sentenca).scalars()

    return render_template('categoria/lista.jinja2',
                           rset=rset)


@bp.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    form = NovoCategoriaForm()
    if form.validate_on_submit():
        categoria = Categoria()
        categoria.nome = form.nome.data
        db.session.add(categoria)
        db.session.commit()
        flash(f"Categoria '{form.nome.data}' adicionada")
        return redirect(url_for('categoria.lista'))

    return render_template('categoria/add_edit.jinja2',
                           title="Nova categoria",
                           form=form)

@bp.route('/edit/<uuid:id_categoria>', methods=['GET', 'POST'])
@login_required
def edit(id_categoria):
    categoria = Categoria.get_by_id(id_categoria)
    if categoria is None:
        flash("Categoria inexistente", category='warning')
        return redirect(url_for('categoria.lista'))

    form = EditCategoriaForm(request.values, obj=categoria)
    if form.validate_on_submit():
        categoria.nome = form.nome.data
        db.session.commit()
        flash("Categoria alterada", category='success')
        return redirect(url_for('categoria.lista'))

    return render_template('categoria/add_edit.jinja2',
                           title="Alterar categoria", form=form)

@bp.route('/del/<uuid:id_categoria>', methods=['GET', 'POST'])
@login_required
def remove(id_categoria):
    categoria = Categoria.get_by_id(id_categoria)
    if categoria is None:
        flash("Categoria inexistente", category='warning')
        return redirect(url_for('categoria.lista'))

    db.session.delete(categoria)
    db.session.commit()
    flash("Categoria removida", category='success')
    return redirect(url_for('categoria.lista'))

src/templates/categoria/add_edit.jinja2
{% extends '_layout.jinja2' %}
{% from 'bootstrap5/form.html' import render_field %}

{% block content %}
    <section class="h-100">
        <div class="container h-100">
            <div class="row justify-content-sm-center h-100">
                <div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
                    <div class="card shadow-lg">
                        <div class="card-body p-5">
                            <form action="" method="post">
                                {{ form.csrf_token }}
                                {{ render_field(form.nome) }}
                                {{ render_field(form.submit) }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

src/templates/categoria/lista.jinja2
{% extends '_layout.jinja2' %}
{% from 'bootstrap5/utils.html' import render_icon %}

{% block content %}
    <table class="table table-striped table-hover">
    <thead><tr>
            <th scope="col">Nome da categoria</th>
            <th scope="col" class="text-center">Operações</th>
    </tr></thead>
    <tbody>
    {% for categoria in rset %}
        <tr><td>{{ categoria.nome }}</td>
            <td class="text-center"><a href="{{ url_for('categoria.remove', id_categoria=categoria.id) }}"
                   onclick="return confirm('Confirma a remoção da categoria?')">
                {{ render_icon('trash', color='danger') }}</a>
                <a href="{{ url_for('categoria.edit', id_categoria=categoria.id) }}">
                    {{ render_icon('pencil-square') }}</a></td></tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}